version: '3.2'
services:

  server:
    volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '../local_mount_point:/opt/remove_mount_point'
    ports:
            - '1024-65535:6565' 
    image: ''
    
    
  grafana:
    ports:
        - '3000:3000'
    container_name: grafana
    image: 'grafana/grafana'
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro #read-only bind mount
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
 

